# Numpy Array Dimensions

1D Array

2D Array

3D Array

In [1]:
import numpy as np      # importing numpy library

In [2]:
A = np.array(5)        # Scalar Array
A

array(5)

In [3]:

np.ndim(A)               # Dimension method

0

In [12]:
One = np.array([1, 2, 3, 4, 5])

In [13]:
One

array([1, 2, 3, 4, 5])

In [14]:
 np.ndim(One)

1

In [15]:
Two = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
Two

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
 np.ndim(Two)


2

In [17]:
Three = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [18]:
Three

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [19]:

np.ndim(Three)

3

# List vs Numpy Array

In [20]:
list1 = [1,4.0,'apple']                     # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [21]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [22]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [23]:
arr = np.array([1, 2, 3, 4, 5])             # Allows Mathematical Operations

# arr/5
# list1/5

# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists



# Reshaping arrays

Reshaping means changing the shape of an array.

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array 
newarr = arr.reshape(4, 3)


In [25]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# 1D to 3D Array 

newarr = arr.reshape(2, 3, 2)


In [27]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [28]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [29]:
print(arr[2] + arr[3])                 # Addition of 2 elements

7


In [30]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array

print(arr[0, 1])                          # 1st row 2nd element
print(arr[1, 4])                          # 2nd row 5th element

2
10


In [31]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

print(arr[0, 1, 2])               # 0th matrix, 2nd row, 3rd column
print(arr[1, 1, 0])               # 1st matrix, 2nd row, 1st column

6
10


In [33]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])