## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [2]:
import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6, 7])             # Slicing 1D Array


In [3]:
a1[1:5]                                       # [start:end]


array([2, 3, 4, 5])

In [4]:
a1[4:]

array([5, 6, 7])

In [5]:
a1[:4]

array([1, 2, 3, 4])

In [6]:
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])      # Slicing 2D Array



In [7]:
 a2[1, 1:4]                                            # [row:column]


array([7, 8, 9])

In [8]:
a2[0:2, 2]


array([3, 8])

In [9]:
a2[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [10]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],          
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])           # # Slicing 3D Array

In [11]:
a3[:2,1:,:2]                                                          # [matrix:row:column]

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])

In [12]:
a3.shape

(3, 3, 3)

# View vs Copy

Copy is a new array, and the View is just a view of the original array.

Any changes made to the **copy** will not affect original array.

Any changes made to the **view** will affect the original array.

In [13]:
arr = np.array([1, 2, 3, 4, 5])

# Copy Method

copy = arr.copy()
copy[0] = 42

print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [14]:
# View Method

view = arr.view()
view[0] = 42

print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


# Append , Insert and Delete Operations

In [15]:
a = np.array([[1,2,3],
              [4,5,6]]) 
 
# Append Method

np.append(a, [7,8,9]) 



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.append(a, [[7,8,9]],axis = 0) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.append(a, [[5],[8]],axis = 1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [18]:
a = np.array([[1,2],
              [3,4],
              [5,6]]) 

# Insert Method

np.insert(a,3,[11,12]) 
 


array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [19]:
np.insert(a,1,[11,12],axis = 0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [20]:
np.insert(a,1,[11,12,13],axis = 1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [21]:
a = np.array([[ 1,  2,  3, 12],
              [ 9,  5,  6,  11],
              [ 8,  4, 10, 7]])

# Delete Method

np.delete(a,9) 


array([ 1,  2,  3, 12,  9,  5,  6, 11,  8, 10,  7])

In [22]:
np.delete(a,1,axis = 1) 


array([[ 1,  3, 12],
       [ 9,  6, 11],
       [ 8, 10,  7]])

In [23]:
np.delete(a,1,axis = 0) 

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

In [24]:
np.ndim(a)

2

# Hstack vs Vstack

Hstack is used to join two arrays **Horizontally**.

Vstack is used to join two arrays **Vertically**.


In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [26]:
print(a,b) 
print(np.ndim(a), np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [27]:
# Performing Hstack

result = np.hstack((a,b))

print(result, np.ndim(result))

[1 2 3 4 5 6] 1


In [28]:
# Performing Vstack

result = np.vstack((a,b))

print(result, np.ndim(result))

[[1 2 3]
 [4 5 6]] 2


# Numpy Concatenation

It is used for joining two or more arrays of the same shape along a specified axis.

Axis = 0, Adding new rows

Axis = 1, Adding new columns


In [ ]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])

arr3 = np.array([[3], [9]])
arr4 = np.array([[4 , 8]])

  
new = np.concatenate((arr1, arr2), axis = 0)
  
print(new)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [ ]:
new = np.concatenate((arr1, arr2), axis = 1)
  
print(new)

[[2 4 3 5]
 [6 8 7 9]]
